[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "wechat-rs"
healthcheckPath = "/admin/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "wechat-rs"
protocol = "HTTP"
internalPort = 3000

[services.networking]
httpPort = true
